@extends('frontend/body/main_master')
@section('frontend')
<main id="main">


    @include('frontend/bim.bim-head')
    <!-- ======= Featured Services Section ======= -->
    <section id="featured-services" class="featured-services">
        <div class="container" data-aos="fade-up">

            <!-- ======= About Section ======= -->
            <section id="about" class="about section-bg">
                <div class="container">

                    <div class="section-title">
                        <h3>SCAN TO BIM
                        </h3>
                    </div>

                    <div data-aos="fade-up" data-aos-delay="100">
                        <h3>SCAN TO BIM

                        </h3>
                        <p><b>SCAN TO BIM/REVIT POINT CLOUD MODELING SERVICES
                            </b></p>
                        <p>Laser Scanning and Scan to BIM technology exists to solve a common issue in the construction industry: as built documents are non-existing or fail to reflect existing conditions showing too many discrepancies and inaccuracies compared to what has been built. Traditional surveying takes too much time, can be inaccurate and only captures a fraction of the information you can get with laser scanning technology. The information obtained from laser scanning is derived from millions of points generated by high technology 3D scanning devices that capture the precise geometry of everything in the facility, creating an accurate digital replication of everything seen with the human eye.

                        </p>
                        <p>
                            Even though this Point Cloud deliverable is very powerful in and of itself, for several different reasons you may need a REVIT Model, or perhaps even 2D CAD As-Builts. Horizons can take these Point Cloud files and create REVIT Models from them.


                        </p>
                        <p>How does it work?

                        </p>
                        <p>During the Scan to BIM process, point clouds composed by millions of data points previously obtained during a 3D laser scanning session on site are converted into accurate 3D Architectural and MEP BIM models which reflect exactly what has actually been built, providing all geometry and data needed for as-built, renovation and documentation purposes.

                        </p>
                        <p>The Horizons Scan to BIM team specializes in tracing these point clouds produced by our scanning team or by 3rd party companies that perform the field Laser Scanning, and in generating Native REVIT models that can serve several purposes, from its utilization as a starting point for architectural/Horizonsineering redesigning of existing buildings and coordinating trades of new construction with existing conditions to capturing As-Built conditions for BIM models that will be utilized for Operations (FM).

                        </p>
                        <p>We utilizes 3rd party and its own tools and know-how to make the tracing process more cost efficient and to ensure the quality of the model.

                        </p>
                    </div>

                </div>
            </section><!-- End About Section -->

        </div>
    </section><!-- End Featured Services Section -->

</main><!-- End #main -->


@endsection